name: Daily Slack Report

on:
  schedule:
    # Agendado para 10:00 UTC (ajuste conforme necessário)
    - cron: '0 10 * * *'
  workflow_dispatch:  # Permite execução manual

jobs:
  send-report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Send report to Slack
        run: python streamlit_slack_reporter.py
        env:
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          SLACK_CHANNEL: '#youtube-analytics' 